### PR TITLE
doc(examples): 01. Quickstart Jupyter Notebook

### PR DESCRIPTION
**Pull request by oktak**
#93 
Added `Quickstart` notebook.

### CODE REVIEW

**Comment by whitead** [comment]
Thank you for the contribution! We'll have it reviewed shortly.

**Comment by whitead** [comment]
Looks good, a few small changes:

1. With the simple compiling instructions, you shouldn't need to do the complex conda instructions even if you are in a separate conda environment. Those instructions are more for if you have lots of conflicting python versions installed, like on a shared compute cluster. I'll add some text to the README about this and let's just refer to the simple instructions for your notebook. 
2. Please remove the code amended. That's good for me to know, but probably not someone trying out hoomd-tf.  You're correct that the `graph.save` order was wrong, thank you!

**Comment by oktak** [comment]
> Looks good, a few small changes:
> 
>     1. With the simple compiling instructions, you shouldn't need to do the complex conda instructions even if you are in a separate conda environment. Those instructions are more for if you have lots of conflicting python versions installed, like on a shared compute cluster. I'll add some text to the README about this and let's just refer to the simple instructions for your notebook.
> 
>     2. Please remove the code amended. That's good for me to know, but probably not someone trying out hoomd-tf.  You're correct that the `graph.save` order was wrong, thank you!

Thanks for your reply. **So your suggestion is to remove the texts, and leave the title and those code blocks. Am I correct?**

1. It's because I want to keep my OS's python environment clean. And I am not sure if the others build the code without conda. So I've chosen to mention it.

2. It's ok for me to remove that. But I think I should add the inline comment to `hoomd.context.initialize("--mode=cpu")` line, because when I call that without any parameters, there will be errors that saying `'-f'` parameter is not defined. Therefore, I suspect that the coder should choose mode GPU or CPU explicitly.

**Comment by whitead** [comment]
Great, thanks. Sure leave the conda instructions you mentioned if you found that using the simple instructions caused issues. 2. Ok please leave the initialization flag in then.

**Comment by oktak** [comment]
Okay, I updated and pushed another commit.

**Comment by whitead** [comment]
@dilnoza92 adding running instructions to the readme sounds like a good idea, but maybe that could be separate from this PR.

**Comment by dilnoza92** [comment]
@whitead yes it can be a new PR.

**Pull request merged**
