### PR TITLE
Update mol_{angle,dihedral,bond_distance} to use tf.gather when cg_positions is a tf.Tensor

### PR DESCRIPTION
**Pull request by RainierBarrett**
This PR is a small optimization to the functions like `mol_angle` that take in CG indices so they can take in the whole list of CG index pairs at once instead of one pair at a time, when CG_positions is a tensor.

### CODE REVIEW

**Comment by whitead** [comment]
@RainierBarrett you still working on this? Looks like you just need to fix your whitespace.

**Comment by geemi725** [comment]
Function updates look good. Will approve when PEP 8 issue is addressed.

**Comment by RainierBarrett** [comment]
@geemi725 I thought [e38da36](https://github.com/ur-whitelab/hoomd-tf/commit/e38da366b0ee81a69500f2ca64c23a36470edd4c) was the only pep8 change needed. Is something else missing?

**Comment by geemi725** [comment]
Oh it's not shown as fixed for some reason. Good job with PR

**Review by geemi725 — APPROVED** [review]

**Comment by whitead** [comment]
Hi @geemi725 and @RainierBarrett, this is still failing due to issue identified by pep8:

```
 E     File "/usr/share/miniconda/lib/python3.7/site-packages/hoomd/htf/utils.py", line 858
E       if type(cg_positions) == tf.Tensor:
E                                         ^
E   TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by RainierBarrett** [comment]
Ahh, I see it was in the test output, not the github bot. I recently set up a new machine and I guess I forgot to configure my editor. I'll address this, give me a little bit.

**Comment by whitead** [comment]
@RainierBarrett  looks MDAnalysis 2.0 version is killing our CI. Can you add MDAnalysis < 2.0 to CI?

**Pull request merged**
