### PR TITLE
Adding Jupyter notebooks to CI

### PR DESCRIPTION
**Pull request by hgandhi2411**
- [x] Run all notebooks as part of CI
- [x] Exclude notebooks that use MDAnalysis when testing, if MDAnalysis not installed

### CODE REVIEW

**Comment by whitead** [comment]
@hgandhi2411 this is really great work, nice job Heta! Is there anyway though you can remove the notebook output from the log file? It makes the log files hard to read.

**Comment by hgandhi2411** [comment]
> @hgandhi2411 this is really great work, nice job Heta! Is there anyway though you can remove the notebook output from the log file? It makes the log files hard to read.

Thanks @whitead. I can look into clearing out the notebook output.

**Comment by hgandhi2411** [comment]
@whitead In the `08. N-Body Neural Force Fields.ipynb` notebook, the following error shows up occasionally and disappears on re-running the notebook. Do we need to worry about it?

```bash
########### Hoomd-Sim Code ################
hoomd.context.initialize('--mode=cpu')

tfcompute = htf.tfcompute(model)

# create a square lattice
system = hoomd.init.create_lattice(unitcell=hoomd.lattice.sq(a=1.2),
                                    n=[16,16])
nlist = hoomd.md.nlist.cell()
# NVT ensemble
hoomd.md.integrate.mode_standard(dt=0.001)
hoomd.md.integrate.nvt(group=hoomd.group.all(), kT=0.1, tau=0.5).randomize_velocities(seed=1)
tfcompute.attach(nlist, r_cut=5, save_output_period=5)
#run with our silly model
hoomd.run(1e3)
------------------

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-127d1819638d> in <module>
     13 tfcompute.attach(nlist, r_cut=5, save_output_period=5)
     14 #run with our silly model
---> 15 hoomd.run(1e3)

/usr/share/miniconda/lib/python3.7/site-packages/hoomd/__init__.py in run(tsteps, profile, limit_hours, limit_multiple, callback_period, callback, quiet)
    199     if not quiet:
    200         context.msg.notice(1, "** starting run **\n");
--> 201     context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
    202     if not quiet:
    203         context.msg.notice(1, "** run complete **\n");

RuntimeError: Error computing cell list
RuntimeError: Error computing cell list

Error: Process completed with exit code 1.
```

**Comment by hgandhi2411** [comment]
@whitead Now only errors are logged when notebooks are run. Let me know if you'd like any other changes.

**Comment by whitead** [comment]
@hgandhi2411 that is bizarre, especially since it uses a random number seed. Can you try adjusting the check period `nlist(check_period=1)`?

**Comment by whitead** [comment]
@hgandhi2411 looks like there are some build errors still

**Comment by hgandhi2411** [comment]
@whitead Everything works now!

**Review by whitead — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
