### PR TITLE
Implement molecular features 

### PR DESCRIPTION
**Pull request by geemi725**
Methods to calculate bond distances, angles, dihedrals added. Addresses #108

### CODE REVIEW

**Comment by hgandhi2411** [comment]
@geemi, can you address the pep8 issues please?

**Comment by hgandhi2411** [comment]
@geemi725 you forgot to push the meth.gsd file. Your test depends on that.

**Comment by hgandhi2411** [comment]
@mehradans92 the second error that you are getting is because you forgot to copy over files. You need to copy `utils.py` in your build directory everytime you pull and it has changed.

**Comment by mehradans92** [comment]
@hgandhi2411 I did copy utils.py but there was no change.

**Comment by geemi725** [comment]
@mehradans92 I think this is because you haven't copied over utils.py in my branch to hoomd-blue/build/hoomd/htf folder

**Comment by hgandhi2411** [comment]
@geemi725 two tests in `test_utils.py` failed because `test_topol.pdb` (for test_trajectory) and `meth20.gsd`(for test_mol_properties) were not found. Make sure you pull from master from time to time so your branch is current.

**Comment by hgandhi2411** [comment]
@geemi725 I kept getting the `FileNotFoundError` but I fixed that. The test takes more than 15 minutes to run for me and still fails with this error:  `**ERROR**: Overflow in nlist! Only 50 space but there are 766 neighbors.`

**Pull request merged**
