### PR TITLE
Added layers and new training options

### PR DESCRIPTION
**Pull request by whitead**
- [x] Move layers and add api doc
- [x] Add unit tests (new file?)
- [x] Add citations to Schnett (RBF) and Shell
- [x] Add layers examples to sphinx doc
- [x] Add to changelog
- [x] version bump
- [x] docs on training keyword

### CODE REVIEW

**Comment by whitead** [comment]
@geemi725 Fixed the GPU issue. Please review. Thanks!

**Comment by geemi725** [comment]
Cannot import hoomd. Gives error `Illegal instruction (core dumped)`

**Comment by whitead** [comment]
I don't think that's related to the PR. Try make clean and rebuild hoomd.

**Review by geemi725 — APPROVED** [review]
Test passed! Had to rebuild Hoomd-blue to address the GPU issue

**Pull request merged**
