### PR TITLE
Added gpu sanity test

### PR DESCRIPTION
**Pull request by whitead**
Please check this test correctly checks for gpu TF and gpu hoomd-blue. Must be run on GPU. Run test with `python test-py/_test_sanity_gpu.py`. File starts with _test so that it is not automatically found by pytest because it should only be used on GPUs. Addresses Issue #140

### CODE REVIEW

**Comment by RainierBarrett** [comment]
I was able to run through the HOOMD-blue cmake and compilation on a GPU node just fine (bhg0022). Got a permission error from BH when trying to run `make install` from the HOOMD-blue build dir:

```
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/hoomd.  Maybe need administrative
  privileges.
```

**Comment by whitead** [comment]
Hi @RainierBarrett that looks like cmake is not finding the correct location for site packages. Please make sure that you have the `export CMAKE_PREFIX_PATH=/path/to/environment` set correctly.

**Comment by geemi725** [comment]
I received this error when I ran the _test_sanity_gpu.py script. ERROR: test_force_overwrite (__main__.test_force_gpu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "_test_gpu_sanity.py", line 14, in test_force_overwrite
    hoomd.context.initialize('--mode=gpu')
  File "/home/gwellawa/.conda/envs/hoomd-tf2/lib/python3.7/site-packages/hoomd/context.py", line 247, in initialize
    exec_conf = _create_exec_conf(mpi_comm);
  File "/home/gwellawa/.conda/envs/hoomd-tf2/lib/python3.7/site-packages/hoomd/context.py", line 293, in _create_exec_conf
    exec_conf = _hoomd.ExecutionConfiguration(exec_mode, gpu_vec, options.min_cpu, options.ignore_display, msg, nrank);
RuntimeError: Error initializing execution configuration

**Comment by whitead** [comment]
Looks like your hoomd-blue version doesn't support GPU?

**Comment by geemi725** [comment]
Test passed in the conda version compiled with hoomd-blue.

**Pull request merged**
