### PR TITLE
Benchmarking via pytest

### PR DESCRIPTION
**Pull request by whitead**
Work in progress. Aiming to incorporate bench marking into both CI and offline with GPU

### CODE REVIEW

**Comment by whitead** [comment]
@geemi725 Ready for review. Added benchmarking code that tracks performance from commit to commit and generates html report that goes into documentation.

**Comment by geemi725** [comment]
For some reason I couldn't generate the html report. When I did `pytest -c pytest-benchmark.ini` it gives the following error. 
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --benchmark-autosave
  inifile: /gpfs/fs2/scratch/gwellawa/hoomd-tf/pytest-benchmark.ini
  rootdir: /gpfs/fs2/scratch/gwellawa/hoomd-tf
```
My current pytest version is 6.2.4

**Comment by whitead** [comment]
@geemi725 updated to help you install those packages

**Comment by geemi725** [comment]
Works fine now!

**Review by geemi725 — APPROVED** [review]

**Pull request merged**
