### PR TITLE
Revised to work with Tensorflow 2.4

### PR DESCRIPTION
**Pull request by whitead**
I removed batch fraction (sample weight) - this was not strictly necessary but I found it to be cluttered and we weren't using it. Had to write a custom training loop - we need to check that metrics are working correctly.

### CODE REVIEW

**Comment by whitead** [comment]
@hgandhi2411 moviepy that was an accident! I didn't mean to have those changes. Will revise.

**Comment by whitead** [comment]
`train_on_batch` is still not working due to #261. Trying to decide if we should update example/docs to use work around, write our own wrapper or wait on resolving https://github.com/tensorflow/tensorflow/issues/47116

**Comment by whitead** [comment]
Just a note for myself: we can get around this by moving the box to be a weight or variable.

**Comment by whitead** [comment]
@mehradans92 and @hgandhi2411 this is ready for review. Had to do a bit of a hack and make the box be an N x 3 x 3 sparse tensor. Should be invisible to users though.

**Review by hgandhi2411 — APPROVED** [review]
LGTM

**Pull request merged**
