### PR TITLE
Generate mapped trajectories from Gromacs AA traj files

### PR DESCRIPTION
**Pull request by geemi725**
Addresses issue #266

### CODE REVIEW

**Comment by geemi725** [comment]
@whitead instead of implementing this in utils.py shall I only make an example notebook?

**Comment by whitead** [comment]
@geemi725 think it's better in utils with a conditional import. Also, we have a few trajectories in our examples directory. Can you use one of those for purposes of this? Thanks!

**Comment by geemi725** [comment]
@whitead I updated the example to read from the trajectory and, compute COMs using the HTF function as we discussed. Thoughts?

**Comment by whitead** [comment]
@geemi725 it looks much better. Can you remove the use of `make_tensor_proto` though? I think you want something like 

```
    mapped_pos = htf.center_of_mass(tf.cast(positions[:,:3],dtype=tf.float64), 
                                                         tf.cast(cg_mapping,dtype=tf.float64), box_size)
    mdbox = u.dimensions
    
    #Let's generate snapshots of each frame and write to a GSD file 
    t.append(htf.create_frame(frame_num, CGnum, CGtypes, CGids, mapped_pos.numpy(), mdbox))
    frame_num += 1
```

**Comment by geemi725** [comment]
@whitead I need a mapped positions as a numpy array. So to use tf.make_ndarray don't I have to use make_tensor_proto?

**Comment by whitead** [comment]
I believe just using `t.numpy()` will convert a tensor into a numpy array.

**Comment by geemi725** [comment]
@whitead addressed your comment. @hgandhi2411 I think this is good for review now.

**Review by hgandhi2411 — CHANGES_REQUESTED** [review]
The function looks good. 
Can you take a look at your tutorial and make sure it works? There are a few errors in file paths and your input file `test_topol.gsd` doesn't exist (maybe you forgot to write it?).

**Comment by geemi725** [comment]
@hgandhi2411 addressed your comments. Thanks!!

**Comment by hgandhi2411** [comment]
@geemi725 Everything looks good to me. I fixed some typos. Also, made hoomd context initialization on cpu since initializing on gpu kept giving me a runtime error.

**Review by hgandhi2411 — APPROVED** [review]

**Pull request merged**
