### PR TITLE
Update to real mdanalysis version in requirements & CI

### PR DESCRIPTION
**Pull request by RainierBarrett**
Accidentally pushed early on the last PR. This should address the 2.0 version of mdanalysis breaking everything.

### CODE REVIEW

**Comment by whitead** [comment]
@RainierBarrett think it's lower case: `pip install mdanalysis  < 2.0`

**Comment by whitead** [comment]
@RainierBarrett Angle brackets are probably being eaten by bash. Try putting expr into quotes

**Review by whitead — APPROVED** [review]

**Comment by IAlibay** [comment]
> This should address the 2.0 version of mdanalysis breaking everything.

Sorry to hear that, we'd be happy to help with any MDAnalysis upgrade issues.

**Comment by whitead** [comment]
Hi @IAlibay, thanks for checking in. We appreciate the great work done by MDAnalysis. Pardon @RainierBarrett's comment, we just got caught off guard.

**Pull request merged**
